name: Deploy to Azure VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Copy files to Azure VM
      uses: appleboy/scp-action@v0.1.7
      with:
        host: 4.206.211.217
        username: azureuser
        key: ${{ secrets.VM_SSH_KEY }}
        source: "./*"
        target: "/var/www/html"

    - name: Restart Nginx
      uses: appleboy/ssh-action@v1
      with:
        host: 4.206.211.217
        username: azureuser
        key: ${{ secrets.VM_SSH_KEY }}
        script: |
          sudo systemctl restart nginx
